type Query {
  Todos(id: String, date: Date): [Todo]
  SummonerInfo(summonerName: String!): SummonerInfo
}

type Todo {
  id: String
  value: String
  notes: String
  isComplete: Boolean
  inProgress: Boolean
  createDate: Date
  lastUpdateDate: Date
  completeDate: Date
  stashedDate: Date
}

type Mutation {
  createTodo(input: TodoInput): Todo
  updateTodo(id: String!, input: TodoInput): Todo
  completeTodo(id: String!, input: completeTodoInput): Todo
  removeTodo(id: String!): String
}

input completeTodoInput {
  isComplete: Boolean
}

input TodoInput {
  value: String
  notes: String
  isComplete: Boolean
  inProgress: Boolean
}
